"use client";

import { FileText, Menu, Plus, Search, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { MarkdownBody } from "@/components/agent/knowledge/KnowledgeDocument";
import { PageHeader } from "@/components/page-header";
import { createMemo, deleteMemo, getMemos, updateMemo } from "@/lib/memos";
import type { Memo } from "@/types/memo";

export function MemosPageClient() {
  const [memos, setMemos] = useState<Memo[]>([]); const [selectedId, setSelectedId] = useState(""); const [query, setQuery] = useState("");
  const [editMemoId, setEditMemoId] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [mobileList, setMobileList] = useState(false);
  const reload = useCallback(async (preferred?: string) => { const items = await getMemos(); setMemos(items); setSelectedId((current) => preferred || (items.some((memo) => memo.id === current) ? current : items[0]?.id ?? "")); }, []);
  useEffect(() => { void Promise.resolve().then(() => reload()).catch((error) => setMessage(error instanceof Error ? error.message : "メモを読み込めませんでした")).finally(() => setLoading(false)); }, [reload]);
  const selected = memos.find((memo) => memo.id === selectedId) ?? null;
  const visible = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? memos.filter((memo) => `${memo.title}\n${memo.content}`.toLowerCase().includes(needle)) : memos; }, [memos, query]);
  const create = async () => { setSaving(true); try { const result = await createMemo(); setEditMemoId(result.id); await reload(result.id); setMobileList(false); } catch (error) { setMessage(error instanceof Error ? error.message : "メモを作成できませんでした"); } finally { setSaving(false); } };
  const remove = async () => { if (!selected || !window.confirm(`「${selected.title}」を削除しますか？`)) return; setSaving(true); try { await deleteMemo(selected.id); await reload(); setMessage("削除しました"); } catch (error) { setMessage(error instanceof Error ? error.message : "削除できませんでした"); } finally { setSaving(false); } };
  const list = <><div className="sticky top-0 z-10 border-b border-[#D8D8D8] bg-white p-3"><button className="flex h-9 w-full items-center justify-center gap-2 rounded-md bg-[#D47A95] text-sm font-medium text-white disabled:opacity-50" disabled={saving} onClick={() => void create()} type="button"><Plus className="h-4 w-4" />新しいメモ</button><label className="mt-3 flex h-9 items-center gap-2 rounded-md border border-[#E5E7EB] px-2"><Search className="h-3.5 w-3.5 text-slate-400" /><input className="min-w-0 flex-1 text-xs outline-none" onChange={(event) => setQuery(event.target.value)} placeholder="タイトル・本文を検索" value={query} />{query ? <button aria-label="検索をクリア" onClick={() => setQuery("")} type="button"><X className="h-3.5 w-3.5" /></button> : null}</label></div><div className="p-2">{visible.map((memo) => <button className={`mb-1 w-full rounded-md px-3 py-3 text-left ${memo.id === selectedId ? "bg-[#FDF0F4]" : "hover:bg-slate-50"}`} key={memo.id} onClick={() => { setSelectedId(memo.id); setMobileList(false); }} type="button"><span className="flex items-center gap-2"><FileText className="h-4 w-4 shrink-0 text-[#B85B77]" /><strong className="truncate text-sm font-medium text-slate-800">{memo.title}</strong></span><span className="mt-1 block truncate pl-6 text-xs text-slate-400">{excerpt(memo.content) || "本文なし"}</span><span className="mt-1 block pl-6 text-[10px] text-slate-300">{formatDate(memo.updatedAt)}</span></button>)}{!loading && !visible.length ? <p className="p-6 text-center text-xs text-slate-400">メモはまだありません</p> : null}</div></>;
  return <section className="min-h-[calc(100vh-120px)]"><PageHeader title="メモ" description="思いついたことをすぐ書き残す場所です" actions={<button className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#D47A95] px-4 text-sm font-medium text-white" disabled={saving} onClick={() => void create()} type="button"><Plus className="h-4 w-4" />新しいメモ</button>} />
    {message ? <p className="mt-4 rounded-md border border-[#F1C2D0] bg-[#FDF0F4] p-3 text-sm text-[#8F3F59]" role="status">{message}</p> : null}
    <button className="mt-4 inline-flex items-center gap-2 rounded-md border bg-white px-3 py-2 text-sm lg:hidden" onClick={() => setMobileList(true)} type="button"><Menu className="h-4 w-4" />メモ一覧</button>
    <div className="mt-5 grid min-h-[72vh] overflow-hidden rounded-md border border-[#D8D8D8] bg-white lg:grid-cols-[300px_minmax(0,1fr)]"><aside className="hidden overflow-y-auto border-r border-[#D8D8D8] lg:block">{list}</aside><main className="min-w-0">{loading ? <p className="p-8 text-sm text-slate-400">読み込み中…</p> : selected ? <MemoEditor autoEdit={editMemoId === selected.id} key={`${selected.id}:${selected.updatedAt}`} memo={selected} onDelete={remove} onSaved={async () => { setEditMemoId(""); await reload(selected.id); setMessage("保存しました"); }} /> : <div className="grid min-h-[60vh] place-items-center text-center"><div><FileText className="mx-auto h-9 w-9 text-slate-300" /><p className="mt-3 text-sm text-slate-500">新しいメモを作成してください</p><button className="mt-4 rounded-md bg-[#D47A95] px-4 py-2 text-sm text-white" onClick={() => void create()} type="button">メモを作る</button></div></div>}</main></div>
    {mobileList ? <div className="fixed inset-0 z-50 bg-black/30" onMouseDown={(event) => { if (event.target === event.currentTarget) setMobileList(false); }}><aside className="h-full w-[min(90vw,360px)] overflow-y-auto bg-white shadow-xl"><div className="flex justify-end border-b p-2"><button aria-label="閉じる" onClick={() => setMobileList(false)} type="button"><X className="h-5 w-5" /></button></div>{list}</aside></div> : null}
  </section>;
}

function MemoEditor({ memo, autoEdit, onSaved, onDelete }: { memo: Memo; autoEdit: boolean; onSaved: () => Promise<void>; onDelete: () => Promise<void> }) {
  const [editing, setEditing] = useState(autoEdit); const [title, setTitle] = useState(memo.title); const [content, setContent] = useState(memo.content); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const save = async () => { if (!title.trim()) return; setSaving(true); setError(""); try { await updateMemo(memo.id, { title: title.trim(), content }); await onSaved(); setEditing(false); } catch (nextError) { setError(nextError instanceof Error ? nextError.message : "保存できませんでした"); } finally { setSaving(false); } };
  return <article className="mx-auto max-w-4xl p-6 sm:p-10"><div className="flex items-start justify-between gap-4 border-b border-slate-200 pb-5">{editing ? <input autoFocus className="min-w-0 flex-1 text-2xl font-semibold outline-none" onChange={(event) => setTitle(event.target.value)} value={title} /> : <h1 className="text-2xl font-semibold">{memo.title}</h1>}<div className="flex shrink-0 gap-2">{editing ? <><button className="h-9 rounded-md border px-3 text-sm" onClick={() => { setTitle(memo.title); setContent(memo.content); setEditing(false); }} type="button">取消</button><button className="h-9 rounded-md bg-[#D47A95] px-4 text-sm text-white disabled:opacity-50" disabled={saving || !title.trim()} onClick={() => void save()} type="button">{saving ? "保存中…" : "保存"}</button></> : <><button className="h-9 rounded-md border px-3 text-sm" onClick={() => setEditing(true)} type="button">編集</button><button aria-label="メモを削除" className="grid h-9 w-9 place-items-center rounded-md border border-red-200 text-red-500" onClick={() => void onDelete()} type="button"><Trash2 className="h-4 w-4" /></button></>}</div></div>{error ? <p className="mt-4 text-sm text-red-600">{error}</p> : null}<div className="mt-6">{editing ? <textarea className="min-h-[55vh] w-full resize-y rounded-md border border-[#D8D8D8] bg-[#FAFAFA] p-4 font-mono text-sm leading-7 outline-none focus:border-[#D47A95]" onChange={(event) => setContent(event.target.value)} placeholder="自由に入力してください。Markdownも使えます。" value={content} /> : memo.content ? <MarkdownBody content={memo.content} /> : <button className="text-sm text-slate-400" onClick={() => setEditing(true)} type="button">クリックしてメモを書く</button>}</div></article>;
}

function excerpt(content: string) { return content.replace(/[#>*_`\-[\]]/g, " ").replace(/\s+/g, " ").trim().slice(0, 70); }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "" : new Intl.DateTimeFormat("ja-JP", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(date); }
