"use client";

import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, FileText, Save } from "lucide-react";
import Link from "next/link";
import type { Route } from "next";
import { useEffect, useMemo, useState } from "react";
import { useTasks } from "@/hooks/useTasks";
import { subscribeProjectRecords, updateProject } from "@/lib/projects";
import type { Project, ProjectDraft } from "@/types/project";

type Tab = "overview" | "tasks" | "history" | "files" | "notes";
const tabs: Array<[Tab, string]> = [["overview", "概要"], ["tasks", "タスク"], ["history", "履歴"], ["files", "ファイル"], ["notes", "メモ"]];
const statusLabel: Record<string, string> = { planning: "計画中", active: "進行中", paused: "一時停止", completed: "完了", archived: "アーカイブ" };

export function ProjectDetailClient({ projectId }: { projectId: string }) {
  const tasks = useTasks();
  const [project, setProject] = useState<Project | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<ProjectDraft | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => subscribeProjectRecords((items) => setProject(items.find((item) => item.id === projectId) ?? null), (error) => setMessage(error.message)), [projectId]);
  const projectTasks = useMemo(() => tasks.tasks.filter((task) => task.projectId === projectId), [projectId, tasks.tasks]);
  const openTasks = projectTasks.filter((task) => task.status !== "completed" && task.status !== "cancelled");
  const beginEdit = () => { if (!project) return; setDraft(toDraft(project)); setEditing(true); };
  const save = async () => { if (!project || !draft) return; try { await updateProject(project.id, draft, project.updatedAt); setEditing(false); setMessage("保存しました"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存できませんでした"); } };
  if (!project) return <section><Link className="inline-flex items-center gap-1 text-sm text-slate-500" href={"/projects" as Route}><ArrowLeft className="h-4 w-4" />プロジェクト一覧</Link><p className="mt-8 text-sm text-slate-400">プロジェクトを読み込んでいます…</p></section>;
  return <section className="pb-10"><Link className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-[#B85B77]" href={"/projects" as Route}><ArrowLeft className="h-4 w-4" />プロジェクト一覧</Link>
    <header className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm text-slate-500">{project.companyName || project.productName || "社内プロジェクト"}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{project.name}</h1><span className="mt-3 inline-flex rounded-full border border-[#F1C2D0] bg-[#FDF0F4] px-3 py-1 text-xs font-medium text-[#8F3F59]">{statusLabel[project.status]}</span></div><button className="h-10 rounded-xl border border-slate-200 px-4 text-sm font-medium text-slate-600 hover:bg-slate-50" onClick={beginEdit} type="button">現在地を更新</button></div>
      <div className="mt-6 grid gap-4 border-t border-slate-100 pt-6 md:grid-cols-[1.5fr_1.2fr_.6fr]"><KeyInfo label="現在地" value={project.currentPosition || project.phase || "未設定"} /><KeyInfo label="次" value={project.nextAction || "未設定"} /><KeyInfo label="期限" value={project.targetDate ? project.targetDate.toDate().toLocaleDateString("ja-JP") : "未設定"} /></div></header>
    {message ? <p className="mt-3 text-xs text-[#B85B77]" role="status">{message}</p> : null}
    <nav className="mt-6 flex gap-6 overflow-x-auto border-b border-slate-200" aria-label="プロジェクト詳細">{tabs.map(([value, label]) => <button className={`h-11 shrink-0 border-b-2 text-sm font-medium ${tab === value ? "border-[#D47A95] text-[#8F3F59]" : "border-transparent text-slate-500"}`} key={value} onClick={() => setTab(value)} type="button">{label}</button>)}</nav>
    <div className="mt-5">{tab === "overview" ? <div className="grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><Card title="概要"><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{project.description || "概要はまだありません。"}</p></Card><Card title="重要情報"><dl className="space-y-4"><Info label="関連会社" value={project.companyName || "なし"} /><Info label="商材" value={project.productName || "なし"} /><Info label="現在の段階" value={project.phase || "未設定"} /><Info label="未完了タスク" value={`${openTasks.length}件`} /></dl></Card></div> : null}
      {tab === "tasks" ? <Card title="正式タスク"><TaskList tasks={projectTasks} /></Card> : null}
      {tab === "history" ? <Card title="更新履歴"><div className="space-y-3">{projectTasks.flatMap((task) => (task.progressLogs ?? []).map((log) => ({ ...log, task: task.title }))).sort((a, b) => b.createdAt.toMillis() - a.createdAt.toMillis()).slice(0, 30).map((log) => <div className="border-l-2 border-slate-200 pl-4" key={log.id}><p className="text-sm font-medium text-slate-700">{log.title}</p><p className="mt-1 text-xs text-slate-400">{log.task} · {log.createdAt.toDate().toLocaleString("ja-JP")}</p></div>) || null}{!projectTasks.some((task) => task.progressLogs?.length) ? <p className="text-sm text-slate-400">履歴はまだありません。</p> : null}</div></Card> : null}
      {tab === "files" ? <Card title="ファイル"><p className="text-sm text-slate-400">プロジェクトファイルはまだ登録されていません。既存ファイル機能の統合までは削除せず、参照先を整理します。</p></Card> : null}
      {tab === "notes" ? <Card title="プロジェクトメモ"><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{project.notes || "メモはまだありません。"}</p><button className="mt-4 h-9 rounded-xl border border-slate-200 px-3 text-sm" onClick={beginEdit} type="button">メモを編集</button></Card> : null}</div>
    {editing && draft ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditing(false); }}><section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-lg font-semibold">プロジェクトの現在を更新</h2><div className="mt-5 grid gap-4"><Field label="現在地"><textarea className="min-h-24" onChange={(event) => setDraft({ ...draft, currentPosition: event.target.value })} value={draft.currentPosition} /></Field><Field label="次"><textarea className="min-h-20" onChange={(event) => setDraft({ ...draft, nextAction: event.target.value })} value={draft.nextAction} /></Field><Field label="段階"><input onChange={(event) => setDraft({ ...draft, phase: event.target.value })} value={draft.phase} /></Field><Field label="期限"><input onChange={(event) => setDraft({ ...draft, targetDate: event.target.value })} type="date" value={draft.targetDate} /></Field><Field label="概要"><textarea className="min-h-28" onChange={(event) => setDraft({ ...draft, description: event.target.value })} value={draft.description} /></Field><Field label="メモ"><textarea className="min-h-28" onChange={(event) => setDraft({ ...draft, notes: event.target.value })} value={draft.notes} /></Field></div><div className="mt-6 flex justify-end gap-2"><button className="h-10 rounded-xl border border-slate-200 px-4 text-sm" onClick={() => setEditing(false)} type="button">キャンセル</button><button className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#D47A95] px-4 text-sm font-medium text-white" onClick={() => void save()} type="button"><Save className="h-4 w-4" />保存</button></div></section></div> : null}
  </section>;
}

function toDraft(project: Project): ProjectDraft { return { name: project.name, type: project.type, status: project.status, phase: project.phase, currentPosition: project.currentPosition, nextAction: project.nextAction, notes: project.notes, companyId: project.companyId ?? "", companyName: project.companyName ?? "", productId: project.productId ?? "", productName: project.productName ?? "", description: project.description, startDate: project.startDate ? project.startDate.toDate().toISOString().slice(0, 10) : "", targetDate: project.targetDate ? project.targetDate.toDate().toISOString().slice(0, 10) : "" }; }
function KeyInfo({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-medium text-slate-400">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm font-medium leading-6 text-slate-800">{value}</p></div>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-base font-semibold text-slate-900">{title}</h2><div className="mt-4">{children}</div></section>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-sm font-medium text-slate-700">{value}</dd></div>; }
function TaskList({ tasks }: { tasks: ReturnType<typeof useTasks>["tasks"] }) { return tasks.length ? <div className="divide-y divide-slate-100">{tasks.map((task) => <div className="grid grid-cols-[20px_minmax(0,1fr)_auto] items-center gap-3 py-3" key={task.id}>{task.status === "completed" ? <CheckCircle2 className="h-4 w-4 text-emerald-500" /> : <Clock3 className="h-4 w-4 text-slate-300" />}<div><p className="text-sm font-medium text-slate-800">{task.title}</p><p className="mt-1 text-xs text-slate-400">{task.assigneeName || "担当者未設定"}</p></div><span className="flex items-center gap-1 text-xs text-slate-500"><CalendarDays className="h-3.5 w-3.5" />{task.dueDate ? task.dueDate.toDate().toLocaleDateString("ja-JP", { month: "numeric", day: "numeric" }) : "期限なし"}</span></div>)}</div> : <p className="text-sm text-slate-400">このプロジェクトの正式タスクはありません。</p>; }
function Field({ label, children }: { label: string; children: React.ReactElement<{ className?: string }> }) { return <label className="grid gap-2 text-sm font-medium text-slate-600">{label}{children && <span className="contents">{children}</span>}</label>; }
