import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import type { Client, Project, RequirementDraft } from "@/domain/types";

interface LocalDemoRequest {
  client?: Client;
  project?: Project;
  draft?: RequirementDraft;
  createdBy?: string;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export async function POST(request: Request) {
  try {
    if (process.env.VERCEL) {
      return NextResponse.json(
        {
          error: "Local demo generation writes files and is available only in the local MOGCIA workspace."
        },
        { status: 409 }
      );
    }

    const body = (await request.json()) as LocalDemoRequest;
    if (!body.client || !body.project) {
      return NextResponse.json({ error: "client and project are required." }, { status: 400 });
    }

    const slug = body.project.id.replace(/[^a-zA-Z0-9-]/g, "-");
    const outputDir = path.join(process.cwd(), "public", "generated-demos", slug);
    const demoUrl = `/generated-demos/${slug}/index.html`;
    const screens = body.draft?.screens ?? ["トップ", "サービス", "予約導線", "公式LINE導線"];
    const features = body.draft?.features ?? body.project.services;

    await mkdir(outputDir, { recursive: true });
    await writeFile(
      path.join(outputDir, "index.html"),
      `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(body.project.name)} Demo</title>
  <style>
    :root { --primary:#D5B5B2; --light:#E9CBC8; --dark:#C79A98; --bg:#F8F4F3; --surface:#F7F3F2; --ink:#1F1F22; --blush:#B97B80; }
    * { box-sizing: border-box; }
    body { margin:0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: var(--bg); color: var(--ink); }
    header { min-height: 88vh; display:grid; align-items:center; padding: 48px 7vw; background: radial-gradient(circle at 80% 10%, var(--light), transparent 34%), linear-gradient(135deg, #fff, var(--surface)); }
    nav { position: fixed; inset: 16px 7vw auto; display:flex; justify-content:space-between; align-items:center; padding:12px 14px; border:1px solid rgba(31,31,34,.08); background:rgba(247,243,242,.82); backdrop-filter: blur(16px); border-radius:10px; }
    .brand { font-weight:700; }
    .cta, button { border:0; border-radius:8px; background:var(--ink); color:white; padding:12px 16px; font-weight:700; text-decoration:none; display:inline-flex; }
    h1 { font-size: clamp(42px, 8vw, 92px); line-height:.96; letter-spacing:0; margin:0; max-width:900px; }
    .lead { max-width:680px; margin:24px 0; font-size:18px; line-height:1.8; color:#555; }
    section { padding:72px 7vw; }
    .grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap:16px; }
    .card { background:white; border:1px solid rgba(31,31,34,.08); border-radius:8px; padding:22px; min-height:150px; }
    .pill { display:inline-flex; border-radius:999px; background:var(--light); padding:6px 10px; font-size:12px; margin-bottom:10px; }
    footer { padding:28px 7vw; color:#777; }
  </style>
</head>
<body>
  <nav><span class="brand">${escapeHtml(body.client.name)}</span><a class="cta" href="#contact">予約・相談</a></nav>
  <header>
    <div>
      <span class="pill">MOGCIA Local Demo</span>
      <h1>${escapeHtml(body.project.name)}</h1>
      <p class="lead">${escapeHtml(body.draft?.summary ?? `${body.client.industry}向けに、予約導線・公式LINE導線・SNS流入導線を確認するためのローカルDemoです。`)}</p>
      <a class="cta" href="#contact">導線を確認する</a>
    </div>
  </header>
  <section>
    <span class="pill">Screens</span>
    <h2>Demo画面構成</h2>
    <div class="grid">${screens.map((screen) => `<div class="card"><h3>${escapeHtml(screen)}</h3><p>本番素材・外部API・DBを使わず、商談確認用のPlaceholderで構成しています。</p></div>`).join("")}</div>
  </section>
  <section id="contact">
    <span class="pill">Features</span>
    <h2>確認する導線</h2>
    <div class="grid">${features.map((feature) => `<div class="card"><h3>${escapeHtml(feature)}</h3><p>Demoではクリック導線と表示内容を確認します。本番連携は契約後タスクで管理します。</p></div>`).join("")}</div>
  </section>
  <footer>Generated by MOGCIA Dev Agent / ${escapeHtml(body.createdBy ?? "local-user")}</footer>
</body>
</html>`
    );

    return NextResponse.json({
      run: {
        id: `local-demo-${body.project.id}-${Date.now()}`,
        projectId: body.project.id,
        clientId: body.client.id,
        status: "generated",
        demoUrl,
        outputPath: outputDir,
        logs: ["テンプレート選定完了", "ダミーデータ生成完了", "Placeholder構成完了", "静的ローカルDemo生成完了"],
        safetyChecks: [
          { id: "no-github", label: "GitHubリポジトリを作成していない", passed: true },
          { id: "no-vercel", label: "Vercelへデプロイしていない", passed: true },
          { id: "no-firebase-project", label: "Firebaseプロジェクトを作成していない", passed: true },
          { id: "no-external-api", label: "外部APIへ接続していない", passed: true },
          { id: "no-real-customer-data", label: "実在顧客データを埋め込んでいない", passed: true },
          { id: "no-secrets", label: "認証情報をコードに含めていない", passed: true }
        ],
        generatedAt: new Date().toISOString(),
        generatedBy: body.createdBy ?? "local-user"
      }
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to generate local demo.";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
