"use client";

import { onAuthStateChanged, signInWithEmailAndPassword, type User } from "firebase/auth";
import Image from "next/image";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { getFirebaseAuth } from "@/lib/firebase/client";
import { extractFamilyName, getUserDisplayName } from "@/lib/user-display";

export default function DesktopConnectClient() {
  const params = useSearchParams(); const pairingId = params.get("id") ?? ""; const secret = params.get("secret") ?? "";
  const [user, setUser] = useState<User | null>(null); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false); const [message, setMessage] = useState(""); const [complete, setComplete] = useState(false);
  const familyName = useMemo(() => extractFamilyName(getUserDisplayName(user)), [user]);
  useEffect(() => { const auth = getFirebaseAuth(); if (!auth) { const timer = window.setTimeout(() => { setMessage("Firebaseが未設定です。"); setLoading(false); }, 0); return () => window.clearTimeout(timer); } return onAuthStateChanged(auth, (next) => { setUser(next); setLoading(false); }); }, []);
  const login = async () => { const auth = getFirebaseAuth(); if (!auth) return; setWorking(true); setMessage(""); try { await signInWithEmailAndPassword(auth, email, password); } catch { setMessage("メールアドレスまたはパスワードを確認してください。"); } finally { setWorking(false); } };
  const approve = async () => { if (!user || !pairingId || !secret) return; setWorking(true); setMessage(""); try { const token = await user.getIdToken(); const response = await fetch("/api/desktop/pairing/approve", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ pairingId, secret }) }); const result = await response.json() as { success: boolean; data?: { message: string }; error?: { message: string } }; if (!result.success) throw new Error(result.error?.message || "連携できませんでした。"); setComplete(true); setMessage(result.data?.message || `${familyName}を連携しました。`); } catch (error) { setMessage(error instanceof Error ? error.message : "連携できませんでした。"); } finally { setWorking(false); } };
  return <main className="grid min-h-screen place-items-center bg-[#FFF7F9] px-5 py-10"><section className="w-full max-w-md rounded-[32px] border border-white bg-white p-8 text-center shadow-xl"><Image alt="MOGCIA" className="mx-auto h-24 w-24 rounded-3xl" height={128} src="/m-dev-agent.png" width={128} /><h1 className="mt-6 text-2xl font-bold">MOGCIA Desktop連携</h1>{!pairingId || !secret ? <p className="mt-5 text-red-600">連携URLが正しくありません。</p> : loading ? <p className="mt-5 text-neutral-500">ログイン状態を確認しています…</p> : complete ? <div className="mt-6 rounded-2xl bg-green-50 p-5 text-green-800"><p className="font-bold">{message}</p><p className="mt-2 text-sm">このページを閉じてください。ターミナルで設定が完了します。</p></div> : user ? <div className="mt-6"><p className="text-neutral-600">ログイン中：{getUserDisplayName(user)}</p><button className="mt-5 h-14 w-full rounded-2xl bg-[#EC6F8B] font-bold text-white disabled:opacity-50" disabled={working} onClick={() => void approve()}>{working ? "連携中…" : `${familyName}を連携`}</button></div> : <form className="mt-6 grid gap-4" onSubmit={(event) => { event.preventDefault(); void login(); }}><input autoComplete="email" className="h-14 rounded-2xl border px-4" onChange={(event) => setEmail(event.target.value)} placeholder="メールアドレス" type="email" value={email} /><input autoComplete="current-password" className="h-14 rounded-2xl border px-4" onChange={(event) => setPassword(event.target.value)} placeholder="パスワード" type="password" value={password} /><button className="h-14 rounded-2xl bg-[#EC6F8B] font-bold text-white disabled:opacity-50" disabled={working || !email || password.length < 6}>{working ? "ログイン中…" : "社員アカウントでログイン"}</button></form>}{message && !complete ? <p className="mt-4 text-sm text-red-600">{message}</p> : null}</section></main>;
}
