"use client";

import { Grip, List, Map as MapIcon, Minus, Plus, Search, Trash2, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { PageHeader } from "@/components/page-header";
import { useWorkspaceOptions } from "@/hooks/useWorkspaceOptions";
import { createSystemMap, createSystemMapCell, deleteSystemMapCell, getSystemMaps, updateSystemMap, updateSystemMapCell } from "@/lib/system-maps";
import { calculateMapProgress, mapStatusLabels, mapStatusOptions } from "@/lib/system-map-utils";
import type { SystemMap, SystemMapBundle, SystemMapCell, SystemMapCellStatus } from "@/types/system-map";

type View = "board" | "list";
type Drag = { id: string; startX: number; startY: number; originX: number; originY: number };
const emptyBundle: SystemMapBundle = { maps: [], cells: [] };
const starterSets = [
  { name: "まず全体を整理", description: "目的・現状・決定・未確定を共有したい", cells: [
    { title: "PURPOSE", hint: "このプロジェクトで実現したいこと\n\n- 誰のためか\n- 何を変えるか", x: 0, y: 0, width: 6, height: 3 },
    { title: "CURRENT STATUS", hint: "今どこまで進んでいるか\n\n- 完了したこと\n- 次にやること", x: 6, y: 0, width: 6, height: 3 },
    { title: "DECISIONS", hint: "すでに決めたことと、その理由", x: 0, y: 3, width: 6, height: 3 },
    { title: "PENDING", hint: "未確定・相談したいこと・詰まり", x: 6, y: 3, width: 6, height: 3 }
  ] },
  { name: "システム開発", description: "仕様と構成を開発メンバーに共有したい", cells: [
    { title: "PURPOSE", hint: "何を、誰のために作るか", x: 0, y: 0, width: 4, height: 3 },
    { title: "RULE", hint: "設計・実装で守る方針", x: 4, y: 0, width: 4, height: 3 },
    { title: "STATUS", hint: "実装済み／作業中／未着手", x: 8, y: 0, width: 4, height: 3 },
    { title: "ARCHITECTURE", hint: "主要技術と役割\n\n例: Next.js / Firebase / Cloud Run", x: 0, y: 3, width: 7, height: 4 },
    { title: "DATABASE", hint: "主要データと関係", x: 7, y: 3, width: 5, height: 4 },
    { title: "PENDING", hint: "未確定事項・技術的な懸念", x: 0, y: 7, width: 12, height: 3 }
  ] },
  { name: "Webサイト制作", description: "目的・トンマナ・構成を揃えたい", cells: [
    { title: "PURPOSE", hint: "サイトの目的と達成したい状態", x: 0, y: 0, width: 4, height: 3 },
    { title: "TARGET", hint: "誰に、何を伝えるか", x: 4, y: 0, width: 4, height: 3 },
    { title: "TONE", hint: "ブランドの雰囲気・避けたい表現", x: 8, y: 0, width: 4, height: 3 },
    { title: "SITE STRUCTURE", hint: "必要なページと導線", x: 0, y: 3, width: 7, height: 4 },
    { title: "DESIGN RULE", hint: "色・書体・余白・写真のルール", x: 7, y: 3, width: 5, height: 4 },
    { title: "TODO / PENDING", hint: "次にやること・確認待ち", x: 0, y: 7, width: 12, height: 3 }
  ] }
] as const;

export function MapsPageClient() {
  const projects = useWorkspaceOptions();
  const [bundle, setBundle] = useState(emptyBundle); const [selectedMapId, setSelectedMapId] = useState(""); const [selectedCellId, setSelectedCellId] = useState("");
  const [view, setView] = useState<View>("board"); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState<SystemMapCellStatus | "all">("all");
  const [createOpen, setCreateOpen] = useState(false); const [editOpen, setEditOpen] = useState(false); const [drag, setDrag] = useState<Drag | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const [addingCell, setAddingCell] = useState(false); const [newCellTitle, setNewCellTitle] = useState("");
  const [seeding, setSeeding] = useState(false);
  const boardRef = useRef<HTMLDivElement>(null);
  const reload = useCallback(async (preferred?: string) => { const next = await getSystemMaps(); setBundle(next); setSelectedMapId((current) => preferred || (next.maps.some((map) => map.id === current) ? current : next.maps[0]?.id ?? "")); }, []);
  useEffect(() => { void Promise.resolve().then(() => reload()).catch((error) => setMessage(error instanceof Error ? error.message : "マップを読み込めませんでした")).finally(() => setLoading(false)); }, [reload]);
  const selectedMap = bundle.maps.find((map) => map.id === selectedMapId) ?? null;
  const cells = useMemo(() => bundle.cells.filter((cell) => cell.mapId === selectedMapId), [bundle.cells, selectedMapId]);
  const selectedCell = cells.find((cell) => cell.id === selectedCellId) ?? null;
  const visibleMaps = bundle.maps.filter((map) => map.title.toLowerCase().includes(query.trim().toLowerCase())); const mappedProjectIds = new Set(bundle.maps.map((map) => map.projectId));
  const patchCell = async (id: string, patch: Partial<SystemMapCell>) => { setBundle((current) => ({ ...current, cells: current.cells.map((cell) => cell.id === id ? { ...cell, ...patch } : cell) })); try { await updateSystemMapCell(id, patch); } catch (error) { setMessage(error instanceof Error ? error.message : "セルを更新できませんでした"); await reload(selectedMapId); } };
  const addCell = async () => { if (!selectedMap || !newCellTitle.trim()) return; const last = [...cells].sort((a, b) => (b.y - a.y) || (b.x - a.x))[0]; const x = last && last.x + last.width + 4 <= 12 ? last.x + last.width : 0; const y = last && x > 0 ? last.y : (last ? last.y + last.height : 0); try { const result = await createSystemMapCell(selectedMap.id, newCellTitle.trim(), x, y); setNewCellTitle(""); setAddingCell(false); await reload(selectedMap.id); setSelectedCellId(result.id); } catch (error) { setMessage(error instanceof Error ? error.message : "セルを作成できませんでした"); } };
  const applyStarter = async (starter: typeof starterSets[number]) => { if (!selectedMap || seeding) return; setSeeding(true); try { for (const cell of starter.cells) { const result = await createSystemMapCell(selectedMap.id, cell.title, cell.x, cell.y); await updateSystemMapCell(result.id, { content: cell.hint, width: cell.width, height: cell.height }); } await reload(selectedMap.id); } catch (error) { setMessage(error instanceof Error ? error.message : "最初のセルを作成できませんでした"); } finally { setSeeding(false); } };
  const beginDrag = (event: ReactPointerEvent, cell: SystemMapCell) => { setDrag({ id: cell.id, startX: event.clientX, startY: event.clientY, originX: cell.x, originY: cell.y }); event.currentTarget.setPointerCapture(event.pointerId); };
  const moveDrag = (event: ReactPointerEvent) => { if (!drag || !boardRef.current) return; const column = boardRef.current.clientWidth / 12; const x = Math.max(0, Math.min(11, drag.originX + Math.round((event.clientX - drag.startX) / column))); const y = Math.max(0, drag.originY + Math.round((event.clientY - drag.startY) / 72)); setBundle((current) => ({ ...current, cells: current.cells.map((cell) => cell.id === drag.id ? { ...cell, x, y } : cell) })); };
  const endDrag = () => { if (!drag) return; const cell = bundle.cells.find((item) => item.id === drag.id); setDrag(null); if (cell) void updateSystemMapCell(cell.id, { x: cell.x, y: cell.y }).catch(() => reload(selectedMapId)); };
  const progress = calculateMapProgress(cells);

  return <section className="pb-10"><PageHeader title="マップ" description="プロジェクトの目的・設計・状況をひと目で共有するボード" />
    {message ? <p className="mt-3 rounded-xl border border-[#F1C2D0] bg-[#FDF0F4] px-4 py-3 text-sm text-[#8F3F59]" role="status">{message}</p> : null}
    <div className="mt-5 grid min-h-[72vh] overflow-hidden rounded-2xl border border-slate-200 bg-white md:grid-cols-[290px_minmax(0,1fr)]">
      <aside className="border-b border-slate-200 md:border-b-0 md:border-r"><div className="border-b border-slate-200 p-3"><label className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3"><Search className="h-4 w-4 text-slate-400" /><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" onChange={(e) => setQuery(e.target.value)} placeholder="プロジェクトを検索" value={query} /></label><button className="mt-2 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#D47A95] text-sm font-medium text-white" onClick={() => setCreateOpen(true)} type="button"><Plus className="h-4 w-4" />マップを作成</button></div>
        <div className="max-h-[calc(100dvh-260px)] overflow-y-auto p-2">{loading ? <p className="p-5 text-center text-sm text-slate-400">読み込み中…</p> : visibleMaps.map((map) => { const mapCells = bundle.cells.filter((cell) => cell.mapId === map.id); const mapProgress = calculateMapProgress(mapCells); return <button className={`mb-1 w-full rounded-xl px-3 py-3 text-left ${selectedMapId === map.id ? "bg-[#FBE8EE]" : "hover:bg-slate-50"}`} key={map.id} onClick={() => { setSelectedMapId(map.id); setSelectedCellId(""); }} type="button"><span className="block truncate text-sm font-medium">{map.title}</span><span className="mt-1 block text-xs text-slate-400">{mapCells.length}セル{mapProgress === null ? "" : ` ・ ${mapProgress}%`}</span></button>; })}</div></aside>
      <main className="min-w-0">{selectedMap ? <><header className="border-b border-slate-200 p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{selectedMap.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{selectedMap.description || "プロジェクト概要はまだありません。"}</p></div><button className="h-9 shrink-0 rounded-xl border border-slate-200 px-3 text-sm" onClick={() => setEditOpen(true)} type="button">編集</button></div>{progress !== null ? <div className="mt-4 max-w-md"><div className="flex justify-between text-xs text-slate-500"><span>進捗対象セル</span><strong className="text-[#8F3F59]">{progress}%</strong></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#D47A95]" style={{ width: `${progress}%` }} /></div></div> : null}</header>
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><div className="flex rounded-xl bg-slate-100 p-1"><ViewButton active={view === "board"} icon={<MapIcon className="h-4 w-4" />} label="ボード" onClick={() => setView("board")} /><ViewButton active={view === "list"} icon={<List className="h-4 w-4" />} label="一覧" onClick={() => setView("list")} /></div>{addingCell ? <form className="flex min-w-[280px] flex-1 justify-end gap-2" onSubmit={(e) => { e.preventDefault(); void addCell(); }}><input autoFocus className="h-9 w-full max-w-xs rounded-xl border border-[#D47A95] px-3 text-sm outline-none ring-2 ring-[#FBE8EE]" onChange={(e) => setNewCellTitle(e.target.value)} placeholder="セルのタイトル（例: DATABASE）" value={newCellTitle} /><button className="h-9 rounded-xl bg-[#D47A95] px-4 text-sm font-medium text-white disabled:opacity-40" disabled={!newCellTitle.trim()} type="submit">追加</button><button className="h-9 px-2 text-sm text-slate-500" onClick={() => { setAddingCell(false); setNewCellTitle(""); }} type="button">取消</button></form> : <button className="flex h-9 items-center gap-2 rounded-xl border border-[#F1C2D0] bg-[#FDF0F4] px-3 text-sm font-medium text-[#8F3F59]" onClick={() => setAddingCell(true)} type="button"><Plus className="h-4 w-4" />セルを追加</button>}</div>
        {view === "board" ? cells.length ? <Board boardRef={boardRef} cells={cells} dragging={drag?.id} onDragEnd={endDrag} onDragMove={moveDrag} onOpen={setSelectedCellId} onPointerDown={beginDrag} onResize={(id, patch) => void patchCell(id, patch)} /> : <StarterGuide busy={seeding} onChoose={(starter) => void applyStarter(starter)} onStartBlank={() => setAddingCell(true)} /> : <CellList cells={cells} filter={statusFilter} onFilter={setStatusFilter} onOpen={setSelectedCellId} />}</> : <div className="grid min-h-[65vh] place-items-center text-center"><div><MapIcon className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 text-sm text-slate-600">プロジェクトのマップを作成してください</p></div></div>}</main>
    </div>
    {createOpen ? <CreateMapModal availableProjects={projects.projects.filter((project) => !mappedProjectIds.has(project.id))} onClose={() => setCreateOpen(false)} onSave={async (input) => { const result = await createSystemMap(input); setCreateOpen(false); await reload(result.id); }} /> : null}
    {editOpen && selectedMap ? <EditMapModal map={selectedMap} onClose={() => setEditOpen(false)} onSave={async (patch) => { await updateSystemMap(selectedMap.id, patch); setEditOpen(false); await reload(selectedMap.id); }} /> : null}
    {selectedCell ? <CellDrawer cell={selectedCell} onClose={() => setSelectedCellId("")} onDelete={async () => { if (!window.confirm("このセルを削除しますか？")) return; await deleteSystemMapCell(selectedCell.id); setSelectedCellId(""); await reload(selectedMapId); }} onSave={async (patch) => { await patchCell(selectedCell.id, patch); setSelectedCellId(""); }} /> : null}
  </section>;
}

function StarterGuide({ busy, onChoose, onStartBlank }: { busy: boolean; onChoose: (starter: typeof starterSets[number]) => void; onStartBlank: () => void }) {
  return <div className="bg-slate-50 p-6 sm:p-10"><div className="mx-auto max-w-3xl"><p className="text-xs font-semibold tracking-[.16em] text-[#B95F7B]">はじめ方</p><h3 className="mt-2 text-xl font-semibold text-slate-900">このマップで、何を共有したいですか？</h3><p className="mt-2 text-sm leading-6 text-slate-500">用途に近いものを選ぶと、書き始めるためのセルとヒントを用意します。不要なセルは後から消せます。</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{starterSets.map((starter) => <button className="rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#D47A95] hover:shadow-md disabled:opacity-50" disabled={busy} key={starter.name} onClick={() => onChoose(starter)} type="button"><strong className="text-sm text-slate-800">{starter.name}</strong><span className="mt-2 block text-xs leading-5 text-slate-500">{starter.description}</span><span className="mt-4 block text-xs font-medium text-[#B95F7B]">{starter.cells.length}個のセルで始める →</span></button>)}</div><button className="mt-6 text-sm text-slate-500 underline decoration-slate-300 underline-offset-4 hover:text-slate-800" disabled={busy} onClick={onStartBlank} type="button">空白からセルを1つ作る</button>{busy ? <p className="mt-3 text-sm text-[#8F3F59]">セルを準備しています…</p> : null}</div></div>;
}

function Board({ boardRef, cells, dragging, onOpen, onPointerDown, onDragMove, onDragEnd, onResize }: { boardRef: React.RefObject<HTMLDivElement | null>; cells: SystemMapCell[]; dragging?: string; onOpen: (id: string) => void; onPointerDown: (event: ReactPointerEvent, cell: SystemMapCell) => void; onDragMove: (event: ReactPointerEvent) => void; onDragEnd: () => void; onResize: (id: string, patch: Partial<SystemMapCell>) => void }) {
  const rows = Math.max(10, ...cells.map((cell) => cell.y + cell.height + 1));
  return <div className="overflow-auto bg-slate-50 p-4"><div className="grid min-w-[760px] grid-cols-12 gap-3" onPointerMove={onDragMove} onPointerUp={onDragEnd} ref={boardRef} style={{ gridTemplateRows: `repeat(${rows}, 60px)` }}>{cells.map((cell) => <article className={`group relative min-h-0 overflow-hidden rounded-2xl border bg-white shadow-sm transition ${dragging === cell.id ? "z-20 border-[#D47A95] shadow-lg" : "border-slate-200 hover:border-[#E6A9BB] hover:shadow-md"}`} key={cell.id} style={{ gridColumn: `${cell.x + 1} / span ${Math.min(cell.width, 12 - cell.x)}`, gridRow: `${cell.y + 1} / span ${cell.height}` }}><button aria-label={`${cell.title}を移動`} className="absolute right-2 top-2 z-10 grid h-8 w-8 cursor-grab touch-none place-items-center rounded-lg text-slate-300 opacity-0 hover:bg-slate-100 hover:text-slate-600 group-hover:opacity-100 active:cursor-grabbing" onPointerDown={(event) => onPointerDown(event, cell)} type="button"><Grip className="h-4 w-4" /></button><button className="flex h-full w-full flex-col p-4 pr-11 text-left" onClick={() => onOpen(cell.id)} type="button"><strong className="w-full truncate text-xs font-semibold tracking-[.12em] text-slate-700">{cell.title}</strong>{cell.content ? <div className="prose prose-sm mt-3 max-w-none overflow-hidden text-sm leading-6 text-slate-600"><ReactMarkdown remarkPlugins={[remarkGfm]}>{cell.content}</ReactMarkdown></div> : <span className="mt-3 text-xs text-slate-300">クリックして内容を追加</span>}<span className="mt-auto flex flex-wrap gap-1 pt-3">{cell.status ? <StatusBadge status={cell.status} /> : null}{cell.tags.slice(0, 3).map((tag) => <span className="text-[10px] text-slate-400" key={tag}>#{tag}</span>)}</span></button><div className="absolute bottom-2 right-2 flex items-center rounded-lg border border-slate-200 bg-white opacity-0 shadow-sm group-hover:opacity-100"><button aria-label="セルを小さく" className="grid h-7 w-7 place-items-center text-slate-400 hover:text-[#8F3F59]" onClick={() => onResize(cell.id, { width: Math.max(2, cell.width - 1), height: Math.max(2, cell.height - 1) })} type="button"><Minus className="h-3 w-3" /></button><span className="text-[9px] text-slate-400">サイズ</span><button aria-label="セルを大きく" className="grid h-7 w-7 place-items-center text-slate-400 hover:text-[#8F3F59]" onClick={() => onResize(cell.id, { width: Math.min(12 - cell.x, cell.width + 1), height: Math.min(20, cell.height + 1) })} type="button"><Plus className="h-3 w-3" /></button></div></article>)}</div></div>;
}

function CellList({ cells, filter, onFilter, onOpen }: { cells: SystemMapCell[]; filter: SystemMapCellStatus | "all"; onFilter: (value: SystemMapCellStatus | "all") => void; onOpen: (id: string) => void }) {
  const rows = cells.filter((cell) => filter === "all" || cell.status === filter);
  return <div className="p-4"><select className="h-9 rounded-xl border border-slate-200 bg-white px-3 text-sm" onChange={(e) => onFilter(e.target.value as SystemMapCellStatus | "all")} value={filter}><option value="all">すべてのステータス</option>{mapStatusOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><div className="mt-4 overflow-x-auto rounded-xl border border-slate-200"><div className="grid min-w-[680px] grid-cols-[1.4fr_130px_1fr_120px] gap-3 bg-slate-50 px-4 py-3 text-xs text-slate-500"><span>セル</span><span>ステータス</span><span>タグ</span><span>更新日</span></div>{rows.map((cell) => <button className="grid w-full min-w-[680px] grid-cols-[1.4fr_130px_1fr_120px] gap-3 border-t border-slate-100 px-4 py-3 text-left text-sm hover:bg-slate-50" key={cell.id} onClick={() => onOpen(cell.id)} type="button"><strong className="truncate font-medium">{cell.title}</strong><span>{cell.status ? mapStatusLabels[cell.status] : "—"}</span><span className="truncate text-slate-500">{cell.tags.map((tag) => `#${tag}`).join(" ") || "—"}</span><span className="text-slate-500">{formatDate(cell.updatedAt)}</span></button>)}</div></div>;
}

function CellDrawer({ cell, onClose, onSave, onDelete }: { cell: SystemMapCell; onClose: () => void; onSave: (patch: Partial<SystemMapCell>) => Promise<void>; onDelete: () => Promise<void> }) {
  const [draft, setDraft] = useState(cell); const [tags, setTags] = useState(cell.tags.join(", "));
  return <div className="fixed inset-0 z-50 bg-slate-950/20" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><aside className="ml-auto h-full w-full max-w-xl overflow-y-auto border-l border-slate-200 bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">セル詳細</h2><button aria-label="閉じる" className="grid h-9 w-9 place-items-center rounded-xl hover:bg-slate-50" onClick={onClose} type="button"><X className="h-5 w-5" /></button></div><div className="mt-5 grid gap-4"><Field label="タイトル"><input className="task-input" onChange={(e) => setDraft({ ...draft, title: e.target.value })} value={draft.title} /></Field><Field label="本文（Markdown）"><textarea className="task-input min-h-64 font-mono text-sm" onChange={(e) => setDraft({ ...draft, content: e.target.value })} placeholder="テキスト、見出し、箇条書き、リンクを記述できます" value={draft.content} /></Field><Field label="ステータス（任意）"><select className="task-input" onChange={(e) => setDraft({ ...draft, status: e.target.value ? e.target.value as SystemMapCellStatus : null })} value={draft.status ?? ""}><option value="">設定しない</option>{mapStatusOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="タグ（カンマ区切り・任意）"><input className="task-input" onChange={(e) => setTags(e.target.value)} placeholder="design, important" value={tags} /></Field><label className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input checked={draft.includeInProgress} onChange={(e) => setDraft({ ...draft, includeInProgress: e.target.checked })} type="checkbox" />このセルをプロジェクト進捗に含める</label><div className="grid grid-cols-2 gap-3"><Field label="横幅（2〜12）"><input className="task-input" max={12} min={2} onChange={(e) => setDraft({ ...draft, width: Number(e.target.value) })} type="number" value={draft.width} /></Field><Field label="高さ（2〜20）"><input className="task-input" max={20} min={2} onChange={(e) => setDraft({ ...draft, height: Number(e.target.value) })} type="number" value={draft.height} /></Field></div></div><div className="mt-6 flex justify-between"><button className="flex h-10 items-center gap-2 rounded-xl border border-red-200 px-3 text-sm text-red-600" onClick={() => void onDelete()} type="button"><Trash2 className="h-4 w-4" />削除</button><button className="h-10 rounded-xl bg-[#D47A95] px-5 text-sm font-medium text-white" disabled={!draft.title.trim()} onClick={() => void onSave({ title: draft.title, content: draft.content, status: draft.status, tags: tags.split(",").map((tag) => tag.trim().replace(/^#/, "")).filter(Boolean), includeInProgress: draft.includeInProgress, width: draft.width, height: draft.height })} type="button">保存</button></div></aside></div>;
}

function CreateMapModal({ availableProjects, onClose, onSave }: { availableProjects: Array<{ id: string; name: string }>; onClose: () => void; onSave: (input: { projectId: string; title: string; description: string }) => Promise<void> }) { const [projectId, setProjectId] = useState(availableProjects[0]?.id ?? ""); const [description, setDescription] = useState(""); const project = availableProjects.find((item) => item.id === projectId); return <Modal title="マップを作成" onClose={onClose}><div className="grid gap-4"><Field label="プロジェクト"><select className="task-input" onChange={(e) => setProjectId(e.target.value)} value={projectId}><option value="">選択してください</option>{availableProjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="プロジェクト概要"><textarea className="task-input min-h-28" onChange={(e) => setDescription(e.target.value)} value={description} /></Field><div className="flex justify-end gap-2"><button className="h-10 rounded-xl border px-4 text-sm" onClick={onClose} type="button">キャンセル</button><button className="h-10 rounded-xl bg-[#D47A95] px-5 text-sm text-white disabled:opacity-40" disabled={!projectId} onClick={() => void onSave({ projectId, title: project?.name ?? "", description })} type="button">作成</button></div></div></Modal>; }
function EditMapModal({ map, onClose, onSave }: { map: SystemMap; onClose: () => void; onSave: (patch: { title: string; description: string }) => Promise<void> }) { const [title, setTitle] = useState(map.title); const [description, setDescription] = useState(map.description); return <Modal title="マップを編集" onClose={onClose}><div className="grid gap-4"><Field label="名称"><input className="task-input" onChange={(e) => setTitle(e.target.value)} value={title} /></Field><Field label="概要"><textarea className="task-input min-h-28" onChange={(e) => setDescription(e.target.value)} value={description} /></Field><div className="flex justify-end"><button className="h-10 rounded-xl bg-[#D47A95] px-5 text-sm text-white" onClick={() => void onSave({ title, description })} type="button">保存</button></div></div></Modal>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/25 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-lg font-semibold">{title}</h2><button onClick={onClose} type="button"><X className="h-5 w-5" /></button></div>{children}</section></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-medium text-slate-600">{label}{children}</label>; }
function ViewButton({ active, icon, label, onClick }: { active: boolean; icon: React.ReactNode; label: string; onClick: () => void }) { return <button className={`flex h-8 items-center gap-2 rounded-lg px-3 text-xs font-medium ${active ? "bg-white text-[#8F3F59] shadow-sm" : "text-slate-500"}`} onClick={onClick} type="button">{icon}{label}</button>; }
function StatusBadge({ status }: { status: SystemMapCellStatus }) { return <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${status === "confirmed" ? "bg-emerald-50 text-emerald-700" : status === "on_hold" ? "bg-slate-100 text-slate-500" : "bg-[#FDF0F4] text-[#8F3F59]"}`}>{mapStatusLabels[status]}</span>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("ja-JP", { month: "numeric", day: "numeric" }).format(date); }
